weather_descriptions = {
    "clear sky": "ясно",
    "few clouds": "невелика хмарність",
    "scattered clouds": "мінлива хмарність",
    "broken clouds": "переважно хмарно",
    "overcast clouds": "хмарно",
    "shower rain": "злива",
    "rain": "дощ",
    "thunderstorm": "гроза",
    "snow": "сніг",
    "thunderstorm with light rain": "невеликий дощ з грозою",
    "thunderstorm with rain": "дощ з грозою",
    "thunderstorm with heavy rain": "сильний дощ з грозою",
    "light thunderstorm": "невелика гроза",
    "heavy thunderstorm": "гроза",
    "ragged thunderstorm": "сильна гроза",
    "thunderstorm with light drizzle": "легка мряка з грозою",
    "thunderstorm with drizzle": "мряка з грозою",
    "thunderstorm with heavy drizzle": "сильна мряка з грозою",
    "light intensity drizzle": "дрібна мряка",
    "drizzle": "мряка",
    "heavy intensity drizzle": "сильна мряка",
    "light intensity drizzle rain": "невелика дрібна мряка",
    "drizzle rain": "дрібний дощ",
    "heavy intensity drizzle rain": "сильний дощ",
    "shower rain and drizzle": "сильний дрібний дощ",
    "shower drizzle": "дощить",
    "light rain": "невеликий дощ",
    "moderate rain": "помірний дощ",
    "heavy intensity rain": "сильний дощ",
    "very heavy rain": "дуже сильний дощ",
    "extreme rain": "злива",
    "freezing rain": "крижаний дощ",
    "light intensity shower rain": "невелика злива",
    "heavy intensity shower rain": "сильна злива",
    "ragged shower rain": "злива",
    "light snow": "невеликий сніг",
    "Snow": "сніг",
    "Heavy snow": "сильний сніг",
    "Sleet": "мокрий сніг",
    "Light shower sleet": "невеликий мокрий сніг",
    "Shower sleet": "сильний мокрий сніг",
    "Light rain and snow": "невеликий сніг з дощем",
    "Rain and snow": "сніг з дощем",
    "Light shower snow": "невеликий снігопад",
    "Shower snow": "снігопад",
    "Heavy shower snow": "сильний снігопад",
    "mist": "туман",
    "Smoke": "дим",
    "Haze": "серпанок",
    "sand/ dust whirls": "клуби піску/пилу",
    "fog": "туман",
    "sand": "пісок",
    "dust": "пил",
    "volcanic ash": "вулканічний попіл",
    "squalls": "шквали",
    "tornado": "торнадо",
}

weather_icons = {
    '01d': '🌞',
    '01n': '🌕',
    '02d': '🌤',
    '02n': '🌤',
    '03d': '🌥',
    '03n': '🌥',
    '04d': '🌥',
    '04n': '🌥',
    '09d': '🌧',
    '09n': '🌧',
    '10d': '🌦',
    '10n': '🌧',
    '11d': '🌩',
    '11n': '🌩',
    '13d': '🌨',
    '13n': '🌨',
    '50d': '💨',
    '50n': '💨',
}
